theme = "anybodyhome"
baseURL = "https://reviews.tammalee.com/"
languageCode = "en-us"
title = "Horror Reviews"
googlefonts = "fonts.googleapis.com/css?family=Della+Respira|Overpass:300,300i,700,700i"

[params]
  subtitle = "Tammy's bare-boned crap reviews"

[taxonomies]
  tag = "tags"
  category = "categories"
  rating = "ratings"

  [outputs]
    home = ["HTML", "JSON"]
    page = ["HTML"]
    post = ["HTML"]

